bot_url: "https://t.me/Collectivity_Bot"
db_file: "bot.db"
serv_port: ":9090"


messages:
  response:
    start: "Привет! Чтобы пользоваться данным ботом, для начала Вам необходимо пройти авторизацю по ссылке: %s.\n Если учетной записи еще нет, то сначала зарегистрируйтесь по ссылке:\n%s"
    redirect_url: "http://tlg-bot:9090"
    register_url: "http://localhost:8080/auth/sign-form"
    auth_link: "http://localhost:8080/auth/tlg/login?redirect_url=http://tlg-bot:9090/?chat_id="
    get_debt_link: "http://localhost:8080/auth/tlg/debt"
    already_authorized: "Вы уже авторизированы. Для получения необходимой информации отправьте соответствующую команду."
    unknown_command: "Я не знаю такой команды :("
    result_debt: "Ваша задолженность: %s"
  error:
    default: "Произошла неизвестная ошибка."
    invalid_url:  "Это невалидная ссылка."
    unable_to_save: "Не удалось сохранить ссылку в Pocket. Попробуйте пожалуйста позже."